version: '2'
services:
    cpms-app:
        image: cpms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cpms-mysql:3306/cpms?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cpms-mysql:
        extends:
            file: mysql.yml
            service: cpms-mysql
